myenv/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from polls.views import password_reset_request
from django.conf.urls.static import static

urlpatterns = [
    path('admin$xd/', admin.site.urls),
    path('', include('polls.urls')),
    path('polls/', include('allauth.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset", password_reset_request, name="password_reset")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myenv/mysite/polls/urls.py
from django.urls import path, include

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('register/', views.register, name='register'),
    path("user/", views.userpage, name="userpage"),
    path('woj/add/', views.crwoj.as_view(), name="addwoj"),
    path('woj/<int:pk>', views.upwoj.as_view(), name="upwoj"),
    path('woj/<int:pk>/del/', views.dewoj.as_view(), name="rmwoj"),
    path('woj/', views.woj, name="woj"),
    path('acode/add/', views.cracode.as_view()),
    path('acode/<int:pk>', views.upacode.as_view()),
    path('acode/<int:pk>/del/', views.deacode.as_view()),
    path('acode/', views.woj, name="acode"),
    path('adres/add/', views.cradres.as_view()),
    path('adres/<int:pk>', views.upadres.as_view(), name='adres_up'),
    path('adres/<int:pk>/del/', views.deadres.as_view(), name='adres_del'),
    path('adres/', views.woj, name="adres"),
    path('adres/test/<int:pk>', views.seeadres.as_view(), name='adres_det'),
    path('stadion/add/', views.crstadion.as_view()),
    path('stadion/<int:pk>', views.upstadion.as_view()),
    path('stadion/<int:pk>/del/', views.destadion.as_view()),
    path('stadion/', views.stadion, name="stadion"),
    path('zawody/', views.zawody, name="zawody"),
    path('zawody/add/', views.crzawody.as_view()),
    path('zawody/<int:pk>', views.upzawody.as_view()),
    path('zawody/<int:pk>/del/', views.dezawody.as_view()),
    path('zawody/<strona>', views.article, name="article"),
    path('team/', views.team, name="team"),
    path('team/add/', views.crteam.as_view()),
    path('team/<int:pk>', views.upteam.as_view()),
    path('team/<int:pk>/del/', views.deteam.as_view()),
    path('osoba/', views.osoba, name="osoba"),
    path('osoba/add/', views.crosoba.as_view()),
    path('osoba/<int:pk>', views.uposoba.as_view()),
    path('osoba/<int:pk>/del/', views.deosoba.as_view()),
    path('dyscyplina/', views.dyscyplina, name='dyscyplina'),
    path('dyscyplina/add/', views.crdyscyplina.as_view()),
    path('dyscyplina/<int:pk>', views.updyscyplina.as_view()),
    path('dyscyplina/<int:pk>/del/', views.dedyscyplina.as_view()),
    path('lista_zawodnikow/', views.lista_zawodnikow, name='lz'),
    path('lista_zawodnikow/add/', views.crlista_zawodnikow.as_view()),
    path('lista_zawodnikow/<int:pk>', views.uplista_zawodnikow.as_view()),
    path('lista_zawodnikow/<int:pk>/del/', views.delista_zawodnikow.as_view()),
    path('szatnia/', views.szatnie, name='szatnia'),
    path('szatnia/add/', views.crszatnie.as_view()),
    path('szatnia/<int:pk>', views.upszatnie.as_view()),
    path('szatnia/<int:pk>/del/', views.deszatnie.as_view()),
    path('test/', views.test),
]

myenv/mysite/polls/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.forms import inlineformset_factory

from django.forms.widgets import NumberInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from .custom_layout_object import *
from rest_framework import serializers

from .models import *

from django import forms


class UserCreationForm(UserCreationForm):
    # email = EmailField(label=_("Email address"), required=True,
    #                    help_text=_("Required."))
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError('Ten adres email jest już zarejestrownay. Spróbuj innego.')
        return email

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('osoba', 'zawody',)


# class ProfileForm2(forms.ModelForm):
#     class Meta:
#         model = ProfileZawodnik
#         fields = ('wiek' 'telefon' 'email' 'adres' 'team')


class WojForm(forms.ModelForm):
    class Meta:
        model = Wojewodztwo
        fields = ('id', 'woj_nazwa')


class AcodeForm2(forms.ModelForm):
    class Meta:
        model = Acode
        fields = ('ZIP', 'Miasto', 'Woj')


class AcodeForm3(forms.ModelForm):
    class Meta:
        model = Acode
        exclude = ()


class AdresForm(forms.ModelForm):
    # category_name = serializers.ReadOnlyField(source='Acode.Miasto')

    class Meta:
        model = Adres
        exclude = ()
        # fields = "__all__"


cos = inlineformset_factory(Acode, Adres, form=AdresForm, fields=['Ulica', 'NrDomu', 'NrLokalu'], extra=1, max_num=1)
cos2 = inlineformset_factory(Adres, Acode, form=AcodeForm3, fields=['Miasto', 'ZIP', 'Woj'], extra=1, max_num=1)


class AcodeForm(forms.ModelForm):

    class Meta:
        model = Acode
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(AcodeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Field('Miasto'),
                Field('ZIP'),
                Field('Woj'),
                Fieldset('Adres 2',
                         Formset('titles')),
                HTML("<br>"),
                ButtonHolder(Submit('submit', 'save')),
            )
        )


class AdresForm2(forms.ModelForm):
    # category_name = serializers.ReadOnlyField(source='Acode.Miasto')

    class Meta:
        model = Adres
        fields = "__all__"


class AdresForm3(forms.ModelForm):

    class Meta:
        model = Adres
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(AdresForm3, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 create-label'
        self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Fieldset('',
                         Formset('titles')),
                HTML("<br>"),
                HTML("Adres 2"),
                Field('Ulica'),
                Field('NrDomu'),
                Field('NrLokalu'),
                ButtonHolder(Submit('submit', 'save')),
            )
        )


class StadionForm(forms.ModelForm):
    class Meta:
        model = Stadion
        fields = 'stadion_nazwa', 'pojemnosc_trybun', 'niepelnosprawni', 'stadion_adres', 'stadion_zdjecie'


class ZawodyForm(forms.ModelForm):
    class Meta:
        model = Zawody
        fields = 'zawody_nazwa', 'zawody_data', 'aff_url', 'stadion',


class VoteForm(forms.ModelForm):
    nawierzchnia = forms.IntegerField(
        widget=NumberInput(attrs={'placeholder': '5', 'type': 'range', 'min': '1', 'max': '10', 'class': 'nawierzchnia', }))
    szatnie = forms.IntegerField(
        widget=NumberInput(attrs={'placeholder': '5', 'type': 'range', 'min': '1', 'max': '10', 'class': 'szatnie', }))
    organizacja = forms.IntegerField(
        widget=NumberInput(attrs={'placeholder': '5', 'type': 'range', 'min': '1', 'max': '10', 'class': 'organizacja', }))

    class Meta:
        model = Vote
        fields = ('nawierzchnia', 'szatnie', 'organizacja')


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'


class OsobaForm(forms.ModelForm):
    class Meta:
        model = Osoba
        fields = '__all__'
        # fields = 'imie', 'nazwisko', 'data_urodzenia', 'telefon', 'email', 'zdjecie', 'adres', 'status', 'team'


class LZForm(forms.ModelForm):
    class Meta:
        model = Lista_Zawodnikow
        fields = '__all__'


class DyscForm(forms.ModelForm):
    class Meta:
        model = Dyscyplina
        fields = 'dyscyplina_nazwa',


class SzatniaForm(forms.ModelForm):
    class Meta:
        model = Szatnia
        fields = '__all__'

myenv/mysite/templates/adres.html
{% extends "header.html" %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h1><b>Adres ID {{ object }}</b></h1>
        </div>
        <div class="card-body">
            <table class="table">
                <!--for inline added titles-->
                {% if object.has_titles %}
                    {% for title in object.has_titles.all %}
                        <tr>
                            <th>Title @{{title.Miasto}}</th>
                            <td>{{title.ZIP}}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
                <!--end-->
                {% if object.subject %}
                    <tr>
                        <th>Subject</th>
                        <td>{{ object.Ulica }}</td>
                    </tr>
                {% endif %}
                {% if object.owner %}
                    <tr>
                        <th>Owner</th>
                        <td>{{ object.NrDomu }}</td>
                    </tr>
                {% endif %}
                {% if object.note %}
                    <tr>
                        <th>Note</th>
                        <td>{{ object.NrLokalu }}</td>
                    </tr>
                {% endif %}
            </table>
            <a class="btn btn-outline-info" href="{% url 'polls:adres_up' pk=object.id %}">Update</a>
            <a class="btn btn-outline-danger" href="{% url 'polls:adres_del' pk=object.id %}">Delete</a>
        </div>
    </div>
{% endblock content %}

myenv/mysite/templates/article.html
{% extends "header.html" %}

{% block content %}

    <!--Article-->
    <div class="article-banner text-center">
        <br><br>
        <div class="container">
            <h1 class="article-heading font-weight-bold">{{ ok.zawody_nazwa }}</h1>
            {% if user.is_superuser %}
                <a href="/zawody/{{ ok.id }}" class="text-muted" >Edit</a>
                <a href="/zawody/{{ ok.id }}/del" class="text-muted" >Delete</a>
            {% endif %}
            <p class="font-weight-bold" style="font-size:15px">{{ ok.zawody_pub }}</p>
        </div>
    </div>
    <div class="container text-center">
        <br>
        <div class="">
            {% now "Y-m-d" as todays_date %}
            {% if todays_date < ok.zawody_data|date:"Y-m-d" %}
                <div class="alert alert-success" role="alert" name="ok">
                    <h4 class="alert-heading">Wydarzenie rozpocznie się </h4>
                    <a class="btn btn btn-outline-success" aria-expanded="false"> {{ ok.zawody_data }}</a><br>
                    <label for="ok"><a href="/zawody/" class="alert-link">zobacz też inne</a></label>
                </div>

            {% else %}
                <div class="alert alert-danger" role="alert">
                    Wydarzenie już się odbyło, zobacz pozostałe <a href="/zawody/" class="alert-link">Lista zawodów</a>
                </div>
                <p>Wydarzenie już się odbyło</p>
                <a class="btn btn btn-outline-danger" aria-expanded="false"> {{ ok.zawody_data }}</a>
            {% endif %}
        </div>
    </div>

    <style>
        .article-banner {
            background-image:
                /* The image fade to white */
                    linear-gradient(to left, rgba(0,0,0,0) 10%, #fff 85%),
                        /* The image used */
                    url("{{ ok.stadion.stadion_zdjecie.url }}");
            /* Set a specific height */
            height:200px;
            /* Create the parallax scrolling effect */
            background-attachment: fixed;
            background-position: center bottom;
            background-repeat: no-repeat;
            background-size: cover;
            z-index: auto;
            position: relative;
        }

        /* all devices up to 786px */
        @media only screen and (max-width:768px) {
            .article-heading {font-size:22px !important;}
        }

        /* devices 768px to 1200px */
        @media only screen and (min-width:768px) and (max-width:1200px) {
            .article-heading {font-size:27px !important;}
        }
    </style>



{% endblock %}

myenv/mysite/templates/dodaj.html
{% extends "header.html" %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
    </form>

{% endblock %}


{#{% load crispy_forms_tags %}#}
{#{% block content %}#}
{#    <div class="container">#}
{#        <div class="card">#}
{#            <div class="card-header">#}
{#                Adres#}
{#            </div>#}
{#            <div class="card-body">#}
{#                {% crispy form %}#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock content %}#}

myenv/mysite/templates/formset.html
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<table>
    {{ formset.management_form|crispy }}

    {% for form in formset.forms %}
        <tr class="{% cycle 'row1' 'row2' 'row3' %} formset_row-{{ formset.prefix }}">
            {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</script>
<script src="{% static '/polls/jquery.formset.js' %}">
</script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'dodaj kolejny',
        deleteText: 'usun',
        prefix: '{{ formset.prefix }}',
    });
</script>

myenv/mysite/templates/header.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>stronka</title>
    <!--Bootstrap CSS-->
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>

{% include 'includes/navbar.html' %}

{% include 'includes/messages.html' %}

{% block content %}

{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover();
    });
</script>
{% include "includes/footer.html" %}

<!-- Optional Javascript -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

myenv/mysite/templates/stadion.html
{% extends "header.html" %}
{% load crispy_forms_filters %}

{% block content %}

    {% load crispy_forms_tags %}

    <!--Films-->
    <div class="container py-5">
        <div class="row">
            <h1 class="font-weight-bold">Stadiony</h1>
            {% if user.is_superuser %}
                <button type="button" class="btn btn-outline-primary align-top" style="font-size:18px; border-radius: 20%; height: 40px;" data-toggle="modal" data-target="#stadionModal">+</button>
            {% elif user.is_authenticated %}
                <a tabindex="0" class="btn-xs btn-outline-danger align-top disabled text-nowrap" style="height: 0" role="button" data-toggle="popover" data-trigger="focus" title="Brak uprawnień" data-content="Nie posiadasz wystarczających uprawnień do tego typu akcji">X</a>
            {% else %}
                <a href="/register/" class="btn btn-outline-primary align-top" style="font-size:18px; border-radius: 20%; height: 40px;">+</a>
            {% endif %}
        </div>

        <hr>
        <br>
        <div class="row">
            {% for s in page_obj %}
                    <div class="col-sm-12 col-md-6 col-lg-4 pb-4">
                        <div class="card h-100" style="border:none">
                            <img src="{{ s.stadion_zdjecie.url }}" class="card-img-top" alt="{{ s.stadion_nazwa }}" style="width: auto; height: 200px; object-fit: scale-down;">
                            <div class="card-body">
                                <div class="row">
                                    <h5 class="card-title">{{ s.stadion_nazwa }}</h5>
                                    {% if user.is_authenticated %}
                                        <a class="align-top text-muted" href="/stadion/{{ s.id }}" style="font-size:8px">Edytuj  </a>
                                        <a class="align-top text-muted" href="/stadion/{{ s.id }}/del" style="font-size:8px">  Usuń</a>
{#                                    {% else %}#}
{#                                        <a class="align-top text-muted" href="/register/" style="font-size:8px">Edytuj  </a>#}
{#                                        <a class="align-top text-muted" href="/register/" style="font-size:8px">  Usuń</a>#}
                                    {% endif %}
                                </div>
                                <a class="btn btn-outline-secondary align-top" data-toggle="collapse" href="#collapse1{{s.pk}}" role="button" aria-expanded="false" aria-controls="collapse{{s.pk}}" style="line-height: 5px; font-size-adjust: inherit;">Cechy</a>
                                <div class="collapse" id="collapse1{{ s.pk }}">
                                    <ul class="card-text text-muted checkbox" style="font-size:12px">
                                        <li><p class="card-text text-muted" style="font-size:12px">Pojemność trybun: {{ s.pojemnosc_trybun }}</p></li>
                                        <li >{% if s.niepelnosprawni == True %}
                                            <p>Przystosowany dla niepełnosprawnych: Owszem</p>
                                        {% else %}
                                            <p>Przystosowany dla niepełnosprawnych: Niezbyt</p>
                                        {% endif %}</li>
                                    </ul>
                                </div>
                                <p class="text-muted" style="font-size:12px">Nawierzchnia: {{ s.naw_av }} | Stan szatni: {{ s.sza_av }} | Organizacja: {{ s.org_av }}</p>
                                <div class="row">
                                    <div class="col-3 text-center">
{#                                        {% if user.is_authenticated %}#}
{#                                            <form method="post">#}
{#                                                {% csrf_token %}#}
{#                                                <input type="hidden" value="{{s.id}}" name="id">#}
{#                                                <button type="submit" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</button>#}
{#                                            </form>#}
{#                                        {% else %}#}
{#                                            <a href="/register/" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</a>#}
{#                                        {% endif %}#}
                                    </div>
                                    <div class="col-4 text-center">
                                        <a class="btn btn-outline-primary" data-toggle="collapse" href="#collapse{{s.id}}" role="button" aria-expanded="false" aria-controls="collapse{{s.id}}">Ocena</a>
                                    </div>
                                </div>
                                <div class="collapse" id="collapse{{s.id}}">
                                    <div class="card card-body shadow">
                                        <h6>Ocena Stadionu: {{ s.stadion_nazwa }}</h6>
                                        <hr>
                                        <form method="post">
                                            {% csrf_token %}
                                            {% for field in vote_form %}
                                                <div class="row">
                                                    <div class="col-10" id="slider_{{field.name}}_{{s.id}}" onclick="sliderUpdate('{{field.name}}', {{s.id}})">{{field|as_crispy_field}}</div>
                                                    <div class="col-2 my-auto">
                                                        <h6 class="text-center"><span id="score_{{field.name}}_{{s.id}}" class=text-primary>5</span></h6>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                            <div class="text-right">
                                                {% if user.is_authenticated %}
                                                    <input type="hidden" value="{{s.id}}" name="stadion">
                                                    <button type="submit" name="score_submit" class="btn btn-outline-primary">Oceń</button>
                                                {% else %}
                                                    <a href="/register/" class="btn btn-outline-primary">Zarejestruj się</a>
                                                {% endif %}
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

            {% endfor %}
        </div>

        <!--Pagination-->
        <div class="container">
            <div class="pagination justify-content-center">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        <!--end of Pagination-->

    </div>

    <script>
        function sliderUpdate(field, pk) {
            document.getElementById("score_" + field + "_" + pk).innerText = document.getElementById("slider_" + field + "_" + pk).getElementsByClassName(field)[0].value;
        }
    </script>

{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>#}
{#    <script>#}
{#        $(document).ready(function(){#}
{#            $('[data-toggle="popover"]').popover();#}
{#        });#}
{#    </script>#}
    <style>
        #id_nawierzchnia, #id_szatnie, #id_organizacja {
            -webkit-appearance: none;
            width: 100%;
            border-radius: 0px;
            height: 25px;
            background: #ffff;
            outline: none;
            opacity: 1;
            -webkit-transition: .2s;
            transition: opacity .2s;
        }

        #id_nawierzchnia::-webkit-slider-runnable-track, #id_szatnie::-webkit-slider-runnable-track, #id_organizacja::-webkit-slider-runnable-track {
            -webkit-appearance: none;
            width: 100%;
            height: 15px;
            border-radius: 0px;
            background: #fff;
            outline: none;
            opacity: 1;
            -webkit-transition: .2s;
            transition: opacity .2s;
        }


        #id_nawierzchnia::-webkit-slider-thumb, #id_szatnie::-webkit-slider-thumb, #id_organizacja::-webkit-slider-thumb {
            -webkit-appearance: none;
            border-radius: 0px;
            appearance: none;
            width: 25px;
            height: 25px;
            background: #007bff;
            cursor: pointer;
        }


        #id_nawierzchnia::-moz-range-thumb, #id_szatnie::-moz-range-thumb, #id_organizacja::-moz-range-thumb {
            -webkit-appearance: none;
            border-radius:0px;
            width: 25px;
            height: 25px;
            background: #007bff;
            cursor: pointer;
        }

        {##id_nawierzchnia::-moz-range-track, #id_szatnie::-moz-range-track, #id_organizacja::-moz-range-track {#}
        {#    -webkit-appearance: none;#}
        {#    border-radius:0px;#}
        {#    width: 25px;#}
        {#    height: 25px;#}
        {#    background: #007bff;#}
        {#    cursor: pointer;#}
        {#}#}
    </style>

    <div class="modal fade" tabindex="-1" id="stadionModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Dodaj Stadion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ test|crispy }}
{#                        <span class="text-muted" style="font-size:12px">Hold down "Control", or "Command" on a Mac, to select more than one.</span>#}
                </div>
                <div class="modal-footer">
                    <button type="submit" name="testo" class="btn btn-primary">Zapisz zmiany</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Zamknij</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

myenv/mysite/templates/usun.html
{% extends "header.html" %}

{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <form method="post">
                    {% csrf_token %}
                    <p class="card-text">Are you sure you want to delete "{{ object }}"?</p>
            </div>
        </div>
        <div class="row justify-content-md-center">
            <button type="submit" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">(ง ͠° ͟ل͜ ͡°)ง</button>
            <a href="/" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">(▀̿Ĺ̯▀̿ ̿) </a>

        </div>
        </form>
    </div>


{% endblock %}